### ISSUE TITLE
Regex Error in latest version of fa-spellchecker (v0.1.0)

### ISSUE THREAD

**Issue by AshkanFeyzollahi** [AshkanFeyzollahi/fa-spellchecker#2]
It seems like something is wrong with the regular expression written in function `faspellchecker.utils.is_persian_word`.

Regular expression written in the function:

```py
return re.fullmatch("^[آ-ی]$+", word) is not None
```

Error:

```
/storage/emulated/0/dev $ python sc.py
Traceback (most recent call last):                                   File "/storage/emulated/0/dev/sc.py", line 5, in <module>
    print(test_spellchecker.correction("سللم"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/faspellchecker/spellchecker.py", line 56, in correction
    return max(self.candidates(word), key=self.word_frequency)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/faspellchecker/spellchecker.py", line 70, in candidates
    self.known([word])
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/faspellchecker/spellchecker.py", line 87, in known
    return set(
           ^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/faspellchecker/spellchecker.py", line 88, in <genexpr>
    word for word in words if word in self.vocabulary or is_persian_word(word)
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/faspellchecker/utils.py", line 20, in is_persian_word
    return re.fullmatch("^[آ-ی]$+", word) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/re/_parser.py", line 682, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 7
/storage/emulated/0/dev $
```

**Comment by AshkanFeyzollahi** [comment]
Realised that the character `$` was placed before the character `+`, which that was the issue that lead to this error, new regular expression:

```py
return re.fullmatch("^[آ-ی]+$", word) is not None
```
